/*
 * Copyright 2011, Stuart Douglas
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

package org.fakereplace.com.google.common.collect;

import java.io.Serializable;

import org.fakereplace.com.google.common.annotations.GwtCompatible;

/**
 * An abstract base class for implementing the <a
 * href="http://en.wikipedia.org/wiki/Decorator_pattern">decorator pattern</a>.
 * The {@link #delegate()} method must be overridden to return the instance
 * being decorated.
 * <p/>
 * This class does <i>not</i> forward the {@code hashCode} and {@code equals}
 * methods through to the backing object, but relies on {@code Object}'s
 * implementation. This is necessary to preserve the symmetry of {@code equals}.
 * Custom definitions of equality are usually based on an interface, such as
 * {@code Set} or {@code List}, so that the implementation of {@code equals} can
 * cast the object being tested for equality to the custom interface. {@code
 * ForwardingObject} implements no such custom interfaces directly; they
 * are implemented only in subclasses. Therefore, forwarding {@code equals}
 * would break symmetry, as the forwarding object might consider itself equal to
 * the object being tested, but the reverse could not be true. This behavior is
 * consistent with the JDK's collection wrappers, such as
 * {@link java.util.Collections#unmodifiableCollection}. Use an
 * interface-specific subclass of {@code ForwardingObject}, such as {@link
 * ForwardingList}, to preserve equality behavior, or override {@code equals}
 * directly.
 * <p/>
 * <p>The {@code toString} method is forwarded to the delegate. Although this
 * class does not implement {@link Serializable}, a serializable subclass may be
 * created since this class has a parameter-less constructor.
 *
 * @author Mike Bostock
 */
@GwtCompatible
public abstract class ForwardingObject {

    /**
     * Sole constructor.
     */
    protected ForwardingObject() {
    }

    /**
     * Returns the backing delegate instance that methods are forwarded to.
     * Abstract subclasses generally override this method with an abstract method
     * that has a more specific return type, such as {@link
     * ForwardingSet#delegate}. Concrete subclasses override this method to supply
     * the instance being decorated.
     */
    protected abstract Object delegate();

    /**
     * Returns the string representation generated by the delegate's
     * {@code toString} method.
     */
    @Override
    public String toString() {
        return delegate().toString();
    }

    /* No equals or hashCode. See class comments for details. */
}
